/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: kaiti16.c                                             *
* Font:        楷体                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Character disabled:  0x20 (32)                                     *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x21 (33)                                     *
* Character disabled:  0x21 (33)                                     *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x50 (80)                                     *
* Character enabled:   0x5173 (20851)                                *
* Character enabled:   0x624B (25163)                                *
* Character enabled:   0x52A8 (21160)                                *
* Character enabled:   0x901A (36890)                                *
* Character enabled:   0x4FE1 (20449)                                *
* Character enabled:   0x7A7A (31354)                                *
* Character enabled:   0x676F (26479)                                *
* Character enabled:   0x7535 (30005)                                *
* Character enabled:   0x963B (38459)                                *
* Character enabled:   0x5BB9 (23481)                                *
* Character enabled:   0x81EA (33258)                                *
* Character enabled:   0x3B4 (948)                                   *
* Character enabled:   0x3C1 (961)                                   *
* Character enabled:   0x3BE (958)                                   *
* Character enabled:   0x3A9 (937)                                   *
* Character enabled:   0x3A3 (931)                                   *
* Character enabled:   0x3B5 (949)                                   *
* Character enabled:   0x4ECB (20171)                                *
* Character enabled:   0x5E38 (24120)                                *
* Character enabled:   0x6570 (25968)                                *
* Character enabled:   0x635F (25439)                                *
* Character enabled:   0x4EA4 (20132)                                *
* Character enabled:   0x6D41 (27969)                                *
* Character enabled:   0x538B (21387)                                *
* Character enabled:   0x76F4 (30452)                                *
* Character enabled:   0x4F53 (20307)                                *
* Character enabled:   0x79EF (31215)                                *
* Character enabled:   0x7387 (29575)                                *
* Character enabled:   0x6CB9 (27833)                                *
* Character enabled:   0x6E29 (28201)                                *
* Character enabled:   0x2103 (8451)                                 *
* Character enabled:   0x91CF (37327)                                *
* Character enabled:   0x4E0A (19978)                                *
* Character enabled:   0x4E0B (19979)                                *
* Character enabled:   0x4E00 (19968)                                *
* Character enabled:   0x4E2A (20010)                                *
* Character enabled:   0x521B (21019)                                *
* Character enabled:   0x5EFA (24314)                                *
* Character enabled:   0x65F6 (26102)                                *
* Character enabled:   0x95F3 (38387)                                *
* Character enabled:   0x95F4 (38388)                                *
* Character disabled:  0x95F3 (38387)                                *
* Character disabled:  0x4E00 (19968)                                *
* Character disabled:  0x4E0A (19978)                                *
* Character disabled:  0x4E0B (19979)                                *
* Character disabled:  0x4E2A (20010)                                *
* Character enabled:   0x957F (38271)                                *
* Character enabled:   0x6309 (25353)                                *
* Character enabled:   0x542F (21551)                                *
* Character enabled:   0x6D4B (27979)                                *
* Character enabled:   0x8BD5 (35797)                                *
* Character enabled:   0x4E09 (19977)                                *
* Character enabled:   0x79D2 (31186)                                *
* Character disabled:  0x79D2 (31186)                                *
* Character enabled:   0x79D2 (31186)                                *
* Character enabled:   0x8FDB (36827)                                *
* Character enabled:   0x884C (34892)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontkaiti16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0020[ 16] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0021[ 16] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____,
  ________,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0022[ 16] = { /* code 0022, QUOTATION MARK */
  ________,
  ________,
  ________,
  __XXXX__,
  __X__X__,
  __X__X__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0023[ 16] = { /* code 0023, NUMBER SIGN */
  ________,
  ________,
  ________,
  __X___X_,
  __X__X__,
  __X__X__,
  XXXXXXXX,
  __X__X__,
  __X__X__,
  __X__X__,
  XXXXXXXX,
  _X___X__,
  _X__X___,
  _X__X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0024[ 16] = { /* code 0024, DOLLAR SIGN */
  ________,
  ________,
  ___X____,
  __XXXX__,
  _XXX_X__,
  _X_X_XX_,
  _XXX____,
  __XX____,
  ___XXX__,
  ___X_XX_,
  _X_X_XX_,
  _X_X_XX_,
  _XXX_X__,
  __XXX___,
  ___X____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0025[ 16] = { /* code 0025, PERCENT SIGN */
  ________,
  ________,
  ________,
  _XX__X__,
  X_X__X__,
  X_X_X___,
  X_XXX___,
  _XX_X___,
  ___X_XX_,
  ___XX_X_,
  __X_X_X_,
  __X_X_X_,
  _X__X_X_,
  _X___XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0026[ 16] = { /* code 0026, AMPERSAND */
  ________,
  ________,
  ________,
  __XXX___,
  __X_XX__,
  __X_XX__,
  __X_X___,
  __XX____,
  _XXX____,
  _X_X__X_,
  XX__X_X_,
  XX___XX_,
  _XX_XXXX,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0027[ 16] = { /* code 0027, APOSTROPHE */
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0028[ 16] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ________,
  ______X_,
  _____X__,
  ____XX__,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  ______X_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0029[ 16] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  ________,
  _X______,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  __X_____,
  _XX_____,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_002A[ 16] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  _XXXXXX_,
  ___XX___,
  __XXXX__,
  _X_XX_X_,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_002B[ 16] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  XXXXXXXX,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_002C[ 16] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  __X_____,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_002D[ 16] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_002E[ 16] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_002F[ 16] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  ________,
  ______X_,
  _____X__,
  _____X__,
  ____X___,
  ____X___,
  ___X____,
  ___X____,
  __X_____,
  __X_____,
  _X______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0030[ 16] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__X__,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  __X_XX__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0031[ 16] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ____X___,
  ___XX___,
  _XXXX___,
  _X_XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0032[ 16] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _____XX_,
  _____X__,
  ____XX__,
  ____X___,
  ___X____,
  __X_____,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0033[ 16] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _____XX_,
  ____XX__,
  ____XX__,
  _____XX_,
  ______X_,
  _X____X_,
  _XX__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0034[ 16] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  _____X__,
  ____XX__,
  ___XXX__,
  ___X_X__,
  __X__X__,
  _XX__X__,
  XX___X__,
  XXXXXXXX,
  _____X__,
  _____X__,
  _____X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0035[ 16] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _XX_____,
  _X______,
  _X______,
  _XXXXX__,
  _____XX_,
  ______X_,
  ______X_,
  XX___XX_,
  _XX_XX__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0036[ 16] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  _____X__,
  ____X___,
  ___XX___,
  ___X____,
  __XX____,
  _XXXXX__,
  XX____X_,
  XX____XX,
  XX____XX,
  XX____XX,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0037[ 16] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  _XXXXXX_,
  ______X_,
  _____XX_,
  _____X__,
  ____XX__,
  ____X___,
  ___XX___,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0038[ 16] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0039[ 16] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  XX____X_,
  XX____X_,
  XX___XX_,
  _XX_XX__,
  __XXXX__,
  ____X___,
  ___XX___,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_003A[ 16] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___XX___,
  ________,
  ________,
  ________,
  ___XX___,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_003B[ 16] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___XX___,
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___X____,
  ___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_003C[ 16] = { /* code 003C, LESS-THAN SIGN */
  ________,
  ________,
  ________,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  _XX_____,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_003D[ 16] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  XXXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_003E[ 16] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  ___X____,
  ____X___,
  _____X__,
  ______X_,
  _____X__,
  ____X___,
  ___X____,
  _XX_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_003F[ 16] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X___XX_,
  _____XX_,
  ____XX__,
  ____X___,
  ___X____,
  ________,
  ________,
  ___XX___,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0040[ 16] = { /* code 0040, COMMERCIAL AT */
  ________,
  ________,
  ________,
  __XXXX__,
  _X____X_,
  X__XXXX_,
  X__X_XX_,
  X_X__XX_,
  X_X_X_X_,
  X_X_X_X_,
  X_X_X_X_,
  X__X_X__,
  _X______,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0041[ 16] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXXX__,
  __X__X__,
  __X__X__,
  _XXXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  XX____XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0042[ 16] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _XXXXX__,
  _XXXXX__,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _XXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0043[ 16] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  _X______,
  _X______,
  _X____X_,
  _X____X_,
  _XX___X_,
  __XX_XX_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0044[ 16] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  _XXXX___,
  _X__XX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XXXXX__,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0045[ 16] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _XXXXXX_,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0046[ 16] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXXX__,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0047[ 16] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  _X______,
  _X__XXX_,
  _X__XXX_,
  _X____X_,
  _XX___X_,
  __XX_XX_,
  ___XX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0048[ 16] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _XXXXXX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0049[ 16] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_004A[ 16] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  _X____X_,
  _X___XX_,
  _XXXXX__,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_004B[ 16] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  _X___XX_,
  _X___X__,
  _X__X___,
  _X_XX___,
  _XXX____,
  _XXXX___,
  _X__X___,
  _X__XX__,
  _X___X__,
  _X___XX_,
  _X____XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_004C[ 16] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_004D[ 16] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,
  ________,
  ________,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX_XXX_,
  _XXXX_X_,
  _X_XX_X_,
  _X_XX_X_,
  _X_XX_X_,
  _X_XX_X_,
  _X_X__X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_004E[ 16] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,
  ________,
  ________,
  _X____X_,
  _XX___X_,
  _XX___X_,
  _XXX__X_,
  _X_X__X_,
  _X_XX_X_,
  _X__X_X_,
  _X__XXX_,
  _X___XX_,
  _X___XX_,
  _X___XX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_004F[ 16] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  XX____X_,
  XX____X_,
  XX____X_,
  _X____X_,
  _X___XX_,
  _XX__X__,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0050[ 16] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XXXXXX_,
  _XXX____,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0051[ 16] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X____X_,
  _X____X_,
  XX____X_,
  XX____X_,
  XX____X_,
  _X__X_X_,
  _X__XXX_,
  _XX__X__,
  ___XXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0052[ 16] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XXXXX__,
  _X__X___,
  _X__XX__,
  _X___X__,
  _X___XX_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0053[ 16] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _X___XX_,
  _XX_____,
  __XX____,
  ___XXX__,
  _____XX_,
  _X____X_,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0054[ 16] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  _XXXXXX_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0055[ 16] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0056[ 16] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,
  ________,
  ________,
  XX____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  _XX__X__,
  __X__X__,
  __X_XX__,
  __XXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0057[ 16] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,
  ________,
  ________,
  X__XX_XX,
  XX_XX_X_,
  XX_XX_X_,
  _X_XX_X_,
  _X_XX_X_,
  _XX_X_X_,
  _XX_X_X_,
  _XX__XX_,
  _XX__XX_,
  _XX__X__,
  _XX__X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0058[ 16] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  _X___XX_,
  _XX__X__,
  __X__X__,
  __XXX___,
  ___XX___,
  ___XX___,
  __XXX___,
  __X_XX__,
  _XX__X__,
  _X___XX_,
  XX____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0059[ 16] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  XX____X_,
  _X___XX_,
  _XX__X__,
  __X_XX__,
  __XXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_005A[ 16] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  _XXXXXX_,
  _____XX_,
  _____X__,
  ____XX__,
  ____X___,
  ___X____,
  __XX____,
  __X_____,
  _XX_____,
  _XXXXXX_,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_005B[ 16] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  ___XXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___XXXX_,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_005C[ 16] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  ________,
  ________,
  _X______,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  ___X____,
  ____X___,
  ____X___,
  ____X___,
  _____X__,
  _____X__,
  ______X_,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_005D[ 16] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  _XXXX___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  ____X___,
  _XXXX___,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_005E[ 16] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  ___XX___,
  __X_XX__,
  _X____X_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_005F[ 16] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0060[ 16] = { /* code 0060, GRAVE ACCENT */
  ________,
  __XX____,
  ___XX___,
  ____X___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0061[ 16] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  ____XXX_,
  _XXX_XX_,
  _X___XX_,
  _X__XXX_,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0062[ 16] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  _X_XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0063[ 16] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _X______,
  _X______,
  _X____X_,
  _XX__XX_,
  __XXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0064[ 16] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ________,
  ______X_,
  ______X_,
  ______X_,
  ______X_,
  _XXXXXX_,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0065[ 16] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _XXXXXX_,
  _X______,
  _X____X_,
  _XX__XX_,
  ___XXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0066[ 16] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  ___XXXX_,
  ___X____,
  ___X____,
  ___X____,
  _XXXXXX_,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0067[ 16] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXXX_,
  _X___X__,
  _X___X__,
  __XXXX__,
  _X______,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0068[ 16] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X_XXXX_,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0069[ 16] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  ___XX___,
  ___X____,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_006A[ 16] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  ____XX__,
  _____X__,
  ________,
  ________,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  _X__XX__,
  _XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_006B[ 16] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X__XX__,
  _X_XX___,
  _XXXX___,
  _XX_X___,
  _X___X__,
  _X___XX_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_006C[ 16] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_006D[ 16] = { /* code 006D, LATIN SMALL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX_XXX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  XX_XX_XX,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_006E[ 16] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X_XXXX_,
  _XX___X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_006F[ 16] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X____X_,
  _XX__XX_,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0070[ 16] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  _X_XX___,
  _X______,
  _X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0071[ 16] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  _X___XX_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX__XX_,
  __XXX_X_,
  ______X_,
  ______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0072[ 16] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_XX__,
  __XX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0073[ 16] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX_____,
  ___XXX__,
  _X____X_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ___X____,
  ___X____,
  ___X____,
  XXXXXX__,
  ___X____,
  ___X____,
  ___X____,
  ___X____,
  ___X__X_,
  ____XXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0075[ 16] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X____X_,
  _X____X_,
  _X____X_,
  _X____X_,
  _X___XX_,
  _XX_XXX_,
  __XXX_X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0076[ 16] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X____X_,
  _XX__XX_,
  __X__X__,
  __X__X__,
  __XXX___,
  ___XX___,
  ___XX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0077[ 16] = { /* code 0077, LATIN SMALL LETTER W */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX_XX_XX,
  XX_XX_X_,
  _X_XX_X_,
  _XX_X_X_,
  _XX__XX_,
  _XX__X__,
  __X__X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0078[ 16] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX__X__,
  __X_XX__,
  ___XX___,
  ___XX___,
  __XXXX__,
  _XX__X__,
  _X____X_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_0079[ 16] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X____X_,
  _XX__XX_,
  __X__X__,
  __X__X__,
  __XXX___,
  ___XX___,
  ___XX___,
  ___X____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_007A[ 16] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXXX_,
  ____XX__,
  ____X___,
  ___X____,
  __X_____,
  _XX_____,
  _XXXXXX_,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_007B[ 16] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  _____XX_,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____X___,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  ____XX__,
  _____X__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_007C[ 16] = { /* code 007C, VERTICAL LINE */
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_007D[ 16] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ___X____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_007E[ 16] = { /* code 007E, TILDE */
  __X_____,
  _XXX__X_,
  _X__XXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <Basic Greek> */
GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_03A3[ 32] = { /* code 03A3, GREEK CAPITAL LETTER SIGMA */
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XXXX____,
  _____XX_,________,
  ______XX,________,
  _______X,X_______,
  ________,XX______,
  ________,XX______,
  _______X,X_______,
  ______XX,________,
  _____XX_,________,
  ____XXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_03A9[ 32] = { /* code 03A9, GREEK CAPITAL LETTER OMEGA */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,XXX_____,
  ____XX__,__XX____,
  ___XX___,___X____,
  ___X____,____X___,
  ___X____,____X___,
  ___X____,____X___,
  ___XX___,___XX___,
  ____X___,___X____,
  ____XX__,_XX_____,
  ____XXX_,_XXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_03B4[ 32] = { /* code 03B4, GREEK SMALL LETTER DELTA */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,XX______,
  _____X__,________,
  ______X_,________,
  _______X,X_______,
  ______XX,XX______,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  _____XX_,_X______,
  _______X,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_03B5[ 32] = { /* code 03B5, GREEK SMALL LETTER EPSILON */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  ______X_,________,
  ______X_,________,
  ______XX,X_______,
  ______X_,________,
  ______X_,________,
  ______X_,_X______,
  _______X,X_______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_03BE[ 32] = { /* code 03BE, GREEK SMALL LETTER XI */
  ________,________,
  ________,________,
  ________,________,
  ______XX,X_______,
  ______X_,________,
  ______XX,X_______,
  ______X_,________,
  _______X,XX______,
  ______X_,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  ______XX,XXX_____,
  ________,__X_____,
  ________,_XX_____,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_03C1[ 32] = { /* code 03C1, GREEK SMALL LETTER RHO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  ______X_,_XX_____,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  _____XXX,_X______,
  _____X_X,X_______,
  _____X__,________,
  _____X__,________};

/* Start of unicode area <Letterlike Symbols> */
GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_2103[ 32] = { /* code 2103, DEGREE CELSIUS */
  ________,________,
  __X_____,________,
  _X_X____,________,
  _X_X____,XXXX____,
  __X___XX,____XX__,
  ______X_,_____X__,
  _____XX_,________,
  _____X__,________,
  _____X__,________,
  _____X__,________,
  _____X__,_____X__,
  _____XX_,_____X__,
  ______XX,____XX__,
  _______X,XXXXX___,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_4E09[ 32] = { /* code 4E09 */
  ________,________,
  ________,________,
  ________,________,
  ________,XXXX____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,_XX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,___XXX__,
  __XXXXXX,XXX__XX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_4EA4[ 32] = { /* code 4EA4 */
  ________,________,
  ______X_,________,
  _______X,________,
  ________,___X____,
  _____XXX,XXXXX___,
  ___XX___,________,
  _____XX_,_XX_____,
  ____XX__,X_______,
  ___X____,X_______,
  _____X__,X_______,
  ______XX,________,
  ______XX,X_______,
  _____X__,_XX_____,
  ___XX___,__XXX___,
  ________,___XXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_4ECB[ 32] = { /* code 4ECB */
  ________,________,
  _______X,________,
  _______X,________,
  ______XX,X_______,
  ______X_,_X______,
  _____X__,__X_____,
  ____XX__,X__XX___,
  ____X_X_,_X__XX__,
  ___X__X_,_X____X_,
  _XX___X_,_X______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,_X______,
  ________,_X______,
  ________,_X______,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_4F53[ 32] = { /* code 4F53 */
  ________,________,
  ________,X_______,
  _____X__,_X______,
  ____XX__,_X______,
  ____X___,_X______,
  ___X____,XXXXX___,
  ___X___X,XX______,
  __X_X___,XXX_____,
  _X__X__X,_X_X____,
  ____X_X_,_X__X___,
  ____XX__,_XX_XX__,
  ____X___,XX______,
  ___X____,_X______,
  ________,_X______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_4FE1[ 32] = { /* code 4FE1 */
  ________,________,
  ________,________,
  _____X__,_XX_____,
  ____X___,__X_____,
  ____X___,_____X__,
  ___X__XX,XXXXX___,
  ___X____,________,
  __X_X___,XXX_____,
  _X__X___,________,
  ____X___,XXX_____,
  ____X___,___X____,
  ____X__X,XXX_X___,
  ____X__X,___X____,
  ____X___,XXXXX___,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5173[ 32] = { /* code 5173 */
  ________,________,
  ________,__X_____,
  ________,__X_____,
  _____XX_,_X______,
  ______X_,_X______,
  ________,XXX_____,
  _____XXX,________,
  _______X,________,
  ______XX,XXXXXX__,
  ___XXX_X,________,
  ______X_,X_______,
  ______X_,_X______,
  _____X__,__X_____,
  ____X___,__XXX___,
  ___X____,___XXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_521B[ 32] = { /* code 521B */
  ________,________,
  ________,________,
  _____X__,____XX__,
  _____X__,_____X__,
  _____XX_,_____X__,
  ____X__X,X_X__X__,
  ___X____,__X__X__,
  ___X__X_,__X__X__,
  __XXXX_X,__X__X__,
  ___X__X_,__X__X__,
  ___X__X_,__X__X__,
  ___X__X_,X____X__,
  ____X___,X____X__,
  ____XXXX,X___XX__,
  ________,____X___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_52A8[ 32] = { /* code 52A8 */
  ________,________,
  ________,________,
  ________,__XX____,
  ________,__X_____,
  ____XXX_,__X_____,
  ________,__XXXX__,
  _______X,XXX__X__,
  _XXXXXX_,__X__X__,
  ____X___,_X___X__,
  ___X__X_,_X___X__,
  ___XXX_X,X___X___,
  __XX____,X___X___,
  _______X,____X___,
  ______X_,__XX____,
  _____X__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_538B[ 32] = { /* code 538B */
  ________,________,
  ________,________,
  ________,___X____,
  ____XXXX,XXX_____,
  ____X___,________,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_XXX____,
  ____X__X,XX______,
  ___X____,_X_X____,
  ___X____,X___X___,
  __X_____,X_______,
  __X_XXXX,XXXXXXX_,
  _X______,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_542F[ 32] = { /* code 542F */
  ________,________,
  ________,________,
  ________,XX______,
  ________,__XX____,
  _____XXX,XX_X____,
  _____X__,__X_____,
  _____X__,_XX_____,
  _____XXX,X_______,
  _____X__,________,
  ____X___,___X____,
  ____X_XX,XXXXX___,
  ___X__X_,___X____,
  ___X__X_,___X____,
  __X___XX,XXXX____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5BB9[ 32] = { /* code 5BB9 */
  ________,________,
  ________,________,
  _______X,________,
  ___X____,XXXXX___,
  ___XXXXX,___XXX__,
  ___X_X__,_X______,
  _____XXX,__X_____,
  ____X__X,________,
  ___X__X_,X_______,
  ______X_,_X______,
  _____X__,__XX____,
  ____XXXX,XXXXXXX_,
  __XX_X__,_XX_____,
  _____X__,_X______,
  ______XX,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5E38[ 32] = { /* code 5E38 */
  ________,________,
  _______X,________,
  ____X__X,__XX____,
  _____X_X,_X______,
  _______X,XXXXXX__,
  ___XXXX_,____XX__,
  __X__XXX,XXXX____,
  __X__X__,_X______,
  ______XX,X_______,
  _______X,XXXX____,
  ____XXXX,___X____,
  ____X__X,___X____,
  ____X__X,_XXX____,
  _______X,__X_____,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_5EFA[ 32] = { /* code 5EFA */
  ________,________,
  ________,_X______,
  ________,_X______,
  ________,_XXXX___,
  ____XX_X,XX_X____,
  ____X___,XXXXXX__,
  ____X__X,_X_X____,
  ___X___X,XXX_____,
  ____X___,_XXX____,
  ____X__X,XX______,
  __X_X__X,XXXXX___,
  ___XX___,_X______,
  ___X_XX_,_X______,
  _XX____X,XX______,
  ________,__XXXX__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_624B[ 32] = { /* code 624B */
  ________,________,
  ________,________,
  ________,XXX_____,
  ______XX,________,
  _______X,________,
  ________,XXX_____,
  ______XX,X_______,
  ________,X_______,
  ______XX,XXXXXXX_,
  __XXXX__,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  _______X,X_______,
  ______XX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6309[ 32] = { /* code 6309 */
  ________,________,
  ________,________,
  ____X___,_X______,
  ____X___,__X_____,
  ____X___,____X___,
  ____XXXX,_XXXXX__,
  __XXX__X,X_______,
  ____XX__,_X______,
  ____X___,_X_XXXX_,
  ___XXXXX,X_XX____,
  __X_X___,X_X_____,
  _X__X___,_XX_____,
  ____X___,_X_XX___,
  ___XX__X,X___XX__,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_635F[ 32] = { /* code 635F */
  ________,________,
  ________,________,
  _____X__,____XX__,
  _____X__,XXXX_X__,
  _____X__,X___X___,
  _____XX_,_XXX____,
  __XXXX__,___XXX__,
  _____XX_,XXX__X__,
  _____X__,X__X_X__,
  ___XXX__,X__X_X__,
  _XX__X__,X_X__X__,
  _____X__,X_X__X__,
  ___X_X__,__XXX___,
  ____XX__,XX___XX_,
  _______X,______X_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6570[ 32] = { /* code 6570 */
  ________,________,
  ________,________,
  _____X__,________,
  _____X_X,__X_____,
  ____XXX_,__X_____,
  _____X_X,__X_____,
  __XXXXX_,_X_XXX__,
  ___X_X_X,X_XX____,
  __X__X_X,___X____,
  _____X__,X_X_____,
  ___XXXX_,_XX_____,
  __X_X_X_,__X_____,
  _____X__,_X_X____,
  ____XXX_,X__XX___,
  __XX____,_____X__,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_65F6[ 32] = { /* code 65F6 */
  ________,________,
  ________,________,
  ________,__XX____,
  ________,__X_____,
  __XXXX__,__X_____,
  __X__X__,__X_____,
  __X__XXX,XXXXXX__,
  __X__X__,__X_____,
  __XXXX_X,__X_____,
  __X__X__,X_X_____,
  __X__X__,___X____,
  __XXXX__,___X____,
  __X__X__,___X____,
  ________,_XX_____,
  ________,__X_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_676F[ 32] = { /* code 676F */
  ________,________,
  ____X___,________,
  ____X___,________,
  ____X___,____XX__,
  ____X___,XXXX____,
  ____X_XX,__X_____,
  __XXXX__,__X_____,
  ____X___,_X______,
  ___XXXX_,_X_X____,
  ___XX_X_,XX__XX__,
  __X_X__X,__X__XX_,
  _X__X_X_,__X_____,
  ____X___,_X______,
  ____X___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6CB9[ 32] = { /* code 6CB9 */
  ________,________,
  ________,________,
  ________,_X______,
  ___XX___,_X______,
  ____X___,_X______,
  ________,_X______,
  ________,_XXXXX__,
  __X___XX,XX___X__,
  ___X__X_,_X___X__,
  ____X_X_,XXX__X__,
  ___X__X_,_X___X__,
  ___X__X_,_X_XXX__,
  ___X__XX,X_X_X___,
  __XX____,____X___,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6D41[ 32] = { /* code 6D41 */
  ________,________,
  ________,________,
  ________,_X______,
  ___X____,________,
  ____X___,XXXXX___,
  _______X,X_______,
  _XX_____,X_XX____,
  __X____X,_XXX____,
  ___X__XX,X_______,
  ___X____,X_X_____,
  ___X__X_,X_X_____,
  __XX__X_,X_X_____,
  __X___X_,X_X___X_,
  __X__X__,X__XXXX_,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6D4B[ 32] = { /* code 6D4B */
  ________,________,
  ________,________,
  ________,_____X__,
  ___X_XXX,XX___X__,
  _____X__,X____X__,
  _____X_X,X__X_X__,
  __X__X_X,X_X__X__,
  __X__X_X,X_X__X__,
  ___X_X_X,X_X__X__,
  __X__XX_,X____X__,
  __X___XX,_____X__,
  __X___X_,XX___X__,
  _____X__,_X_X_X__,
  ________,____XX__,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_6E29[ 32] = { /* code 6E29 */
  ________,________,
  ________,________,
  ________,___X____,
  ___XX_XX,XXX_X___,
  ____X__X,___XX___,
  _______X,XXXX____,
  __X____X,_XXX____,
  _______X,X_______,
  ________,____X___,
  ___XX_XX,XXXXXX__,
  ___X__X_,X_X_X___,
  ___X__X_,X_X_X___,
  __X___X_,XX__XX__,
  __X_XXXX,__XX____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_7387[ 32] = { /* code 7387 */
  ________,________,
  _______X,________,
  _______X,XXX_____,
  _____XXX,________,
  ______X_,_X_X____,
  ___XX_XX,X_______,
  ____XX_X,___X____,
  ___X__X_,XX__X___,
  ___X_XXX,________,
  ________,X___XXX_,
  _XXXXXXX,XXXX____,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_7535[ 32] = { /* code 7535 */
  ________,________,
  ________,________,
  ______XX,________,
  ______X_,________,
  ______X_,_XXX____,
  __XXXXXX,X_XX____,
  ___X__X_,__XX____,
  ___X_XXX,X_X_____,
  ___XX_X_,__X_____,
  ___X__XX,XX______,
  ____XXX_,________,
  ______X_,_____X__,
  ______X_,_____X__,
  _______X,XXXXXX__,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_76F4[ 32] = { /* code 76F4 */
  ________,________,
  _______X,X_______,
  _______X,________,
  _______X,_XXX____,
  ____XXXX,X_______,
  ______X_,________,
  _____XXX,XXX_____,
  _____X__,__X_____,
  _____XXX,__X_____,
  _____X__,__X_____,
  _____XXX,__X_____,
  _____XXX,XX______,
  _____X__,_X______,
  _____XXX,XXXXXXX_,
  __XXX___,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_79D2[ 32] = { /* code 79D2 */
  ________,________,
  ________,________,
  ______X_,__X_____,
  _____XX_,__X_____,
  ___XX___,__X_____,
  _____X__,__X__XX_,
  ___XXX__,X_X_____,
  __X_X___,X_X_X___,
  ____XXXX,__X_X___,
  ___XX___,___X____,
  __X_X___,___X____,
  _X__X___,__X_____,
  ____X___,_X______,
  ________,X_______,
  _______X,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_79EF[ 32] = { /* code 79EF */
  ________,________,
  ________,________,
  ______X_,________,
  ____XX__,________,
  _____X__,____X___,
  _____XX_,XXXXXX__,
  ___XX___,X___X___,
  __X_X___,X___X___,
  ____XX__,_XXXX___,
  ___XX_X_,________,
  __X_X___,_X__X___,
  _X__X___,X____X__,
  ____X__X,______X_,
  ____X___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_7A7A[ 32] = { /* code 7A7A */
  ________,________,
  ________,________,
  _______X,X_______,
  ________,________,
  ___X__XX,XXXXX___,
  ___XXX__,____XX__,
  __X__XX_,_X______,
  _____X__,_XX_____,
  ____X___,__X_____,
  ___X____,_XX_____,
  _____XXX,X_______,
  _______X,________,
  _______X,________,
  ______XX,XXXXXX__,
  ___XXX__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_81EA[ 32] = { /* code 81EA */
  ________,________,
  _______X,________,
  _______X,________,
  ______X_,________,
  ______X_,_XX_____,
  ____XX_X,X_XX____,
  ____X___,___X____,
  ____X___,___X____,
  _____XXX,___X____,
  ____X___,___X____,
  _____XXX,X__X____,
  ____X___,___X____,
  ____X___,XX_X____,
  _____XXX,__XX____,
  ________,__X_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_884C[ 32] = { /* code 884C */
  ________,________,
  ________,________,
  _____X__,________,
  ____X___,__XXX___,
  ___X____,_X______,
  __X__X__,________,
  ____X___,___XXXX_,
  ____X_XX,XXX_____,
  ___XX___,__X_____,
  __X_X___,__X_____,
  _X__X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,_XX_____,
  ________,__X_____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_8BD5[ 32] = { /* code 8BD5 */
  ________,________,
  ________,________,
  ________,_X______,
  ____XX__,_X_XX___,
  ________,_X__X___,
  ________,_X______,
  ________,_XX_____,
  _XXXX___,XX______,
  ___X____,__X_____,
  ___X__XX,XXX_____,
  ___X___X,___X____,
  ___X_X_X,_X_X__X_,
  ___XXXXX,X___X_X_,
  ________,_____XX_,
  ________,______X_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_8FDB[ 32] = { /* code 8FDB */
  ________,________,
  ________,________,
  ________,__X_____,
  ___X___X,__X_____,
  ____X__X,__X_____,
  ______XX,XXXX____,
  _______X,__X_____,
  ___XX__X,__XXXX__,
  ___X_XXX,XXX_____,
  ___X___X,__X_____,
  ___X___X,__X_____,
  ___X__X_,__X_____,
  _XX_XX__,__X_____,
  ______XX,XXXXXXX_,
  ________,__XXX___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_901A[ 32] = { /* code 901A */
  ________,________,
  ________,________,
  ________,_XXXX___,
  ___X___X,X__X____,
  ___XX___,XXX_____,
  ________,__XXX___,
  _______X,XX__X___,
  ___XX__X,_XX_X___,
  __XX___X,XX__X___,
  ___X___X,XXX_X___,
  ___X__X_,_X__X___,
  ___X__X_,_XXXX___,
  _XX_XXX_,___X____,
  _______X,XXXXXXX_,
  ________,__XXX___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_91CF[ 32] = { /* code 91CF */
  ________,________,
  ________,________,
  _____XXX,XXXX____,
  _____XXX,X_X_____,
  _____X__,_X______,
  _____XXX,X_______,
  _____XXX,XXXXXXX_,
  __XXX___,_XX_____,
  ____XXXX,X_XX____,
  ____X_XX,__X_____,
  _____X_X,XX______,
  ______XX,________,
  _____XXX,XX______,
  _______X,________,
  __XXXXXX,XXXXX___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_957F[ 32] = { /* code 957F */
  ________,________,
  ________,________,
  _____XX_,_XX_____,
  _____X__,_X______,
  _____X__,X_______,
  _____X_X,________,
  ______X_,__XXX___,
  ____XXXX,XX______,
  ___X_X_X,________,
  _____X__,X_______,
  _____X__,_XX_____,
  _____X__,X_XX____,
  _____XXX,___XXX__,
  _____XX_,________,
  _____X__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_95F4[ 32] = { /* code 95F4 */
  ________,________,
  ________,________,
  ____XX__,___XX___,
  _____X_X,XXX_X___,
  ___X____,____X___,
  ___X____,XX__X___,
  ___X__XX,_X__X___,
  ___X__X_,_X__X___,
  ___X__XX,XX__X___,
  ___X__X_,_X__X___,
  ___X__XX,XX__X___,
  ___X____,_X__X___,
  ___X____,____X___,
  ________,___XX___,
  ________,____X___,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontkaiti16_963B[ 32] = { /* code 963B */
  ________,________,
  ________,________,
  _____X__,________,
  __XXXX__,___X____,
  __X_X___,XXX_X___,
  __X_X___,X___X___,
  __X__X__,XXX_X___,
  __X__X__,X__X____,
  __X__X__,X__X____,
  __X_____,XX_X____,
  __X_____,X__X____,
  __X_____,X__X____,
  __X___XX,XXXXXXX_,
  __X_____,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontkaiti16_CharInfo[140] = {
   {   8,   8,  1, acGUI_Fontkaiti16_0020 } /* code 0020 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0021 } /* code 0021 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0022 } /* code 0022 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0023 } /* code 0023 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0025 } /* code 0025 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0026 } /* code 0026 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0027 } /* code 0027 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0028 } /* code 0028 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0029 } /* code 0029 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_002A } /* code 002A */
  ,{   8,   8,  1, acGUI_Fontkaiti16_002B } /* code 002B */
  ,{   8,   8,  1, acGUI_Fontkaiti16_002C } /* code 002C */
  ,{   8,   8,  1, acGUI_Fontkaiti16_002D } /* code 002D */
  ,{   8,   8,  1, acGUI_Fontkaiti16_002E } /* code 002E */
  ,{   8,   8,  1, acGUI_Fontkaiti16_002F } /* code 002F */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0030 } /* code 0030 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0031 } /* code 0031 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0032 } /* code 0032 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0033 } /* code 0033 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0034 } /* code 0034 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0035 } /* code 0035 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0036 } /* code 0036 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0037 } /* code 0037 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0038 } /* code 0038 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0039 } /* code 0039 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_003A } /* code 003A */
  ,{   8,   8,  1, acGUI_Fontkaiti16_003B } /* code 003B */
  ,{   8,   8,  1, acGUI_Fontkaiti16_003C } /* code 003C */
  ,{   8,   8,  1, acGUI_Fontkaiti16_003D } /* code 003D */
  ,{   8,   8,  1, acGUI_Fontkaiti16_003E } /* code 003E */
  ,{   8,   8,  1, acGUI_Fontkaiti16_003F } /* code 003F */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0040 } /* code 0040 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0041 } /* code 0041 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0042 } /* code 0042 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0043 } /* code 0043 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0044 } /* code 0044 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0045 } /* code 0045 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0046 } /* code 0046 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0047 } /* code 0047 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0048 } /* code 0048 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0049 } /* code 0049 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_004A } /* code 004A */
  ,{   8,   8,  1, acGUI_Fontkaiti16_004B } /* code 004B */
  ,{   8,   8,  1, acGUI_Fontkaiti16_004C } /* code 004C */
  ,{   8,   8,  1, acGUI_Fontkaiti16_004D } /* code 004D */
  ,{   8,   8,  1, acGUI_Fontkaiti16_004E } /* code 004E */
  ,{   8,   8,  1, acGUI_Fontkaiti16_004F } /* code 004F */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0050 } /* code 0050 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0051 } /* code 0051 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0052 } /* code 0052 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0053 } /* code 0053 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0054 } /* code 0054 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0055 } /* code 0055 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0056 } /* code 0056 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0057 } /* code 0057 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0058 } /* code 0058 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0059 } /* code 0059 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_005A } /* code 005A */
  ,{   8,   8,  1, acGUI_Fontkaiti16_005B } /* code 005B */
  ,{   8,   8,  1, acGUI_Fontkaiti16_005C } /* code 005C */
  ,{   8,   8,  1, acGUI_Fontkaiti16_005D } /* code 005D */
  ,{   8,   8,  1, acGUI_Fontkaiti16_005E } /* code 005E */
  ,{   8,   8,  1, acGUI_Fontkaiti16_005F } /* code 005F */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0060 } /* code 0060 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0061 } /* code 0061 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0062 } /* code 0062 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0063 } /* code 0063 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0064 } /* code 0064 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0065 } /* code 0065 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0066 } /* code 0066 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0067 } /* code 0067 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0068 } /* code 0068 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0069 } /* code 0069 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_006A } /* code 006A */
  ,{   8,   8,  1, acGUI_Fontkaiti16_006B } /* code 006B */
  ,{   8,   8,  1, acGUI_Fontkaiti16_006C } /* code 006C */
  ,{   8,   8,  1, acGUI_Fontkaiti16_006D } /* code 006D */
  ,{   8,   8,  1, acGUI_Fontkaiti16_006E } /* code 006E */
  ,{   8,   8,  1, acGUI_Fontkaiti16_006F } /* code 006F */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0070 } /* code 0070 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0071 } /* code 0071 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0072 } /* code 0072 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0073 } /* code 0073 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0074 } /* code 0074 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0075 } /* code 0075 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0076 } /* code 0076 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0077 } /* code 0077 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0078 } /* code 0078 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_0079 } /* code 0079 */
  ,{   8,   8,  1, acGUI_Fontkaiti16_007A } /* code 007A */
  ,{   8,   8,  1, acGUI_Fontkaiti16_007B } /* code 007B */
  ,{   8,   8,  1, acGUI_Fontkaiti16_007C } /* code 007C */
  ,{   8,   8,  1, acGUI_Fontkaiti16_007D } /* code 007D */
  ,{   8,   8,  1, acGUI_Fontkaiti16_007E } /* code 007E */
  ,{  16,  16,  2, acGUI_Fontkaiti16_03A3 } /* code 03A3 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_03A9 } /* code 03A9 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_03B4 } /* code 03B4 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_03B5 } /* code 03B5 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_03BE } /* code 03BE */
  ,{  16,  16,  2, acGUI_Fontkaiti16_03C1 } /* code 03C1 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_2103 } /* code 2103 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_4E09 } /* code 4E09 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_4EA4 } /* code 4EA4 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_4ECB } /* code 4ECB */
  ,{  16,  16,  2, acGUI_Fontkaiti16_4F53 } /* code 4F53 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_4FE1 } /* code 4FE1 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_5173 } /* code 5173 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_521B } /* code 521B */
  ,{  16,  16,  2, acGUI_Fontkaiti16_52A8 } /* code 52A8 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_538B } /* code 538B */
  ,{  16,  16,  2, acGUI_Fontkaiti16_542F } /* code 542F */
  ,{  16,  16,  2, acGUI_Fontkaiti16_5BB9 } /* code 5BB9 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_5E38 } /* code 5E38 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_5EFA } /* code 5EFA */
  ,{  16,  16,  2, acGUI_Fontkaiti16_624B } /* code 624B */
  ,{  16,  16,  2, acGUI_Fontkaiti16_6309 } /* code 6309 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_635F } /* code 635F */
  ,{  16,  16,  2, acGUI_Fontkaiti16_6570 } /* code 6570 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_65F6 } /* code 65F6 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_676F } /* code 676F */
  ,{  16,  16,  2, acGUI_Fontkaiti16_6CB9 } /* code 6CB9 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_6D41 } /* code 6D41 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_6D4B } /* code 6D4B */
  ,{  16,  16,  2, acGUI_Fontkaiti16_6E29 } /* code 6E29 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_7387 } /* code 7387 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_76F4 } /* code 76F4 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_79D2 } /* code 79D2 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_79EF } /* code 79EF */
  ,{  16,  16,  2, acGUI_Fontkaiti16_7A7A } /* code 7A7A */
  ,{  16,  16,  2, acGUI_Fontkaiti16_81EA } /* code 81EA */
  ,{  16,  16,  2, acGUI_Fontkaiti16_884C } /* code 884C */
  ,{  16,  16,  2, acGUI_Fontkaiti16_8BD5 } /* code 8BD5 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_8FDB } /* code 8FDB */
  ,{  16,  16,  2, acGUI_Fontkaiti16_901A } /* code 901A */
  ,{  16,  16,  2, acGUI_Fontkaiti16_91CF } /* code 91CF */
  ,{  16,  16,  2, acGUI_Fontkaiti16_957F } /* code 957F */
  ,{  16,  16,  2, acGUI_Fontkaiti16_95F4 } /* code 95F4 */
  ,{  16,  16,  2, acGUI_Fontkaiti16_963B } /* code 963B */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop45 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[139] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop44 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[138] /* address of first character */
  ,&GUI_Fontkaiti16_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop43 = {
   0x957F /* first character */
  ,0x957F /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[137] /* address of first character */
  ,&GUI_Fontkaiti16_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop42 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[136] /* address of first character */
  ,&GUI_Fontkaiti16_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop41 = {
   0x901A /* first character */
  ,0x901A /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[135] /* address of first character */
  ,&GUI_Fontkaiti16_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop40 = {
   0x8FDB /* first character */
  ,0x8FDB /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[134] /* address of first character */
  ,&GUI_Fontkaiti16_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop39 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[133] /* address of first character */
  ,&GUI_Fontkaiti16_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop38 = {
   0x884C /* first character */
  ,0x884C /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[132] /* address of first character */
  ,&GUI_Fontkaiti16_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop37 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[131] /* address of first character */
  ,&GUI_Fontkaiti16_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop36 = {
   0x7A7A /* first character */
  ,0x7A7A /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[130] /* address of first character */
  ,&GUI_Fontkaiti16_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop35 = {
   0x79EF /* first character */
  ,0x79EF /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[129] /* address of first character */
  ,&GUI_Fontkaiti16_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop34 = {
   0x79D2 /* first character */
  ,0x79D2 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[128] /* address of first character */
  ,&GUI_Fontkaiti16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop33 = {
   0x76F4 /* first character */
  ,0x76F4 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[127] /* address of first character */
  ,&GUI_Fontkaiti16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop32 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[126] /* address of first character */
  ,&GUI_Fontkaiti16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop31 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[125] /* address of first character */
  ,&GUI_Fontkaiti16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop30 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[124] /* address of first character */
  ,&GUI_Fontkaiti16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop29 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[123] /* address of first character */
  ,&GUI_Fontkaiti16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop28 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[122] /* address of first character */
  ,&GUI_Fontkaiti16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop27 = {
   0x6CB9 /* first character */
  ,0x6CB9 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[121] /* address of first character */
  ,&GUI_Fontkaiti16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop26 = {
   0x676F /* first character */
  ,0x676F /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[120] /* address of first character */
  ,&GUI_Fontkaiti16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop25 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[119] /* address of first character */
  ,&GUI_Fontkaiti16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop24 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[118] /* address of first character */
  ,&GUI_Fontkaiti16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop23 = {
   0x635F /* first character */
  ,0x635F /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[117] /* address of first character */
  ,&GUI_Fontkaiti16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop22 = {
   0x6309 /* first character */
  ,0x6309 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[116] /* address of first character */
  ,&GUI_Fontkaiti16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop21 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[115] /* address of first character */
  ,&GUI_Fontkaiti16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop20 = {
   0x5EFA /* first character */
  ,0x5EFA /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[114] /* address of first character */
  ,&GUI_Fontkaiti16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop19 = {
   0x5E38 /* first character */
  ,0x5E38 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[113] /* address of first character */
  ,&GUI_Fontkaiti16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop18 = {
   0x5BB9 /* first character */
  ,0x5BB9 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[112] /* address of first character */
  ,&GUI_Fontkaiti16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop17 = {
   0x542F /* first character */
  ,0x542F /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[111] /* address of first character */
  ,&GUI_Fontkaiti16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop16 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[110] /* address of first character */
  ,&GUI_Fontkaiti16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop15 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[109] /* address of first character */
  ,&GUI_Fontkaiti16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop14 = {
   0x521B /* first character */
  ,0x521B /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[108] /* address of first character */
  ,&GUI_Fontkaiti16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop13 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[107] /* address of first character */
  ,&GUI_Fontkaiti16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop12 = {
   0x4FE1 /* first character */
  ,0x4FE1 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[106] /* address of first character */
  ,&GUI_Fontkaiti16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop11 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[105] /* address of first character */
  ,&GUI_Fontkaiti16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop10 = {
   0x4ECB /* first character */
  ,0x4ECB /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[104] /* address of first character */
  ,&GUI_Fontkaiti16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop9 = {
   0x4EA4 /* first character */
  ,0x4EA4 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[103] /* address of first character */
  ,&GUI_Fontkaiti16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop8 = {
   0x4E09 /* first character */
  ,0x4E09 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[102] /* address of first character */
  ,&GUI_Fontkaiti16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop7 = {
   0x2103 /* first character */
  ,0x2103 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[101] /* address of first character */
  ,&GUI_Fontkaiti16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop6 = {
   0x03C1 /* first character */
  ,0x03C1 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[100] /* address of first character */
  ,&GUI_Fontkaiti16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop5 = {
   0x03BE /* first character */
  ,0x03BE /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 99] /* address of first character */
  ,&GUI_Fontkaiti16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop4 = {
   0x03B4 /* first character */
  ,0x03B5 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 97] /* address of first character */
  ,&GUI_Fontkaiti16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop3 = {
   0x03A9 /* first character */
  ,0x03A9 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 96] /* address of first character */
  ,&GUI_Fontkaiti16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop2 = {
   0x03A3 /* first character */
  ,0x03A3 /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[ 95] /* address of first character */
  ,&GUI_Fontkaiti16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontkaiti16_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_Fontkaiti16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontkaiti16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontkaiti16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontkaiti16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

