/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: weiruanyahei20.c                                      *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x6CB9 (27833)                                *
* Character enabled:   0x6CB9 (27833)                                *
* Character enabled:   0x6837 (26679)                                *
* Character enabled:   0x6D4B (27979)                                *
* Character enabled:   0x5386 (21382)                                *
* Character enabled:   0x53F2 (21490)                                *
* Character enabled:   0x6570 (25968)                                *
* Character enabled:   0x636E (25454)                                *
* Character enabled:   0x8C03 (35843)                                *
* Character enabled:   0x6574 (25972)                                *
* Character enabled:   0x65F6 (26102)                                *
* Character enabled:   0x949F (38047)                                *
* Character enabled:   0x8BED (35821)                                *
* Character enabled:   0x8AFD (35581)                                *
* Character enabled:   0x8A00 (35328)                                *
* Character disabled:  0x8AFD (35581)                                *
* Character enabled:   0x8BD5 (35797)                                *
* Character enabled:   0x4ECB (20171)                                *
* Character enabled:   0x8D28 (36136)                                *
* Character enabled:   0x635F (25439)                                *
* Character enabled:   0x8017 (32791)                                *
* Character enabled:   0x4EA4 (20132)                                *
* Character enabled:   0x6D41 (27969)                                *
* Character enabled:   0x9891 (39057)                                *
* Character enabled:   0x7387 (29575)                                *
* Character enabled:   0x4F53 (20307)                                *
* Character disabled:  0x4F53 (20307)                                *
* Character enabled:   0x4F53 (20307)                                *
* Character enabled:   0x79EF (31215)                                *
* Character enabled:   0x7535 (30005)                                *
* Character enabled:   0x963B (38459)                                *
* Character enabled:   0x52A0 (21152)                                *
* Character enabled:   0x70ED (28909)                                *
* Character enabled:   0x542F (21551)                                *
* Character enabled:   0x65B9 (26041)                                *
* Character enabled:   0x5F0F (24335)                                *
* Character enabled:   0x7A7A (31354)                                *
* Character enabled:   0x676F (26479)                                *
* Character enabled:   0x5BB9 (23481)                                *
* Character enabled:   0x81EA (33258)                                *
* Character enabled:   0x52A8 (21160)                                *
* Character enabled:   0x624B (25163)                                *
* Character enabled:   0x4E00 (19968)                                *
* Character enabled:   0x4E0A (19978)                                *
* Character enabled:   0x4E0B (19979)                                *
* Character enabled:   0x4E2A (20010)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontweiruanyahei20;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_4E00[ 40] = { /* code 4E00, <CJK Ideograph, First> */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_4E0A[ 40] = { /* code 4E0A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,XXXXX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_4E0B[ 40] = { /* code 4E0B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXXXXX__,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______XX,X_______,
  ______X_,XX______,
  ______X_,__XX____,
  ______X_,___XX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_4E2A[ 40] = { /* code 4E2A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _____XXX,________,
  _____X_X,________,
  ____X___,X_______,
  __XX__X_,_X______,
  _XX___X_,__XX____,
  X_____X_,___XX___,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_4EA4[ 40] = { /* code 4EA4 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXX___,
  ____X___,X_______,
  ___X____,_XX_____,
  _XX_X___,_XXX____,
  XX__XX__,XX__X___,
  _____X__,X_______,
  ______XX,________,
  _____XXX,________,
  ___XXX__,XX______,
  _XX_____,__XXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_4ECB[ 40] = { /* code 4ECB */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ___XX___,__X_____,
  __XX____,___X____,
  XX__X___,_X__XX__,
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,_X______,
  __XX____,_X______,
  _XX_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_4F53[ 40] = { /* code 4F53 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,X_______,
  __XX____,X_______,
  __X_XXXX,XXXXX___,
  __X____X,XX______,
  _XX____X,XX______,
  XXX___X_,XX______,
  X_X___X_,X_X_____,
  __X__X__,X_X_____,
  __X__XXX,XXXX____,
  __X_X___,X__X____,
  __XX____,X___X___,
  __X_____,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_52A0[ 40] = { /* code 52A0 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,________,
  __X_____,________,
  __X_____,XXXXX___,
  XXXXXX__,X___X___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  _X___X__,X___X___,
  _X___X__,XXXXX___,
  X_XXXX__,X___X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_52A8[ 40] = { /* code 52A8 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,_X______,
  __XXXXX_,_X______,
  ________,_X______,
  _______X,XXXXX___,
  ________,_X__X___,
  _XXXXXXX,_X__X___,
  ___X____,_X__X___,
  ___X____,_X__X___,
  __X__X__,X___X___,
  __X_XXX_,X___X___,
  _XXX__XX,____X___,
  ______X_,__XXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_5386[ 40] = { /* code 5386 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,________,
  __X____X,________,
  __X____X,________,
  __X_XXXX,XXXX____,
  __X____X,___X____,
  __X____X,___X____,
  __X____X,___X____,
  __X___X_,___X____,
  _X___XX_,___X____,
  _X__XX__,___X____,
  X__XX___,XXX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_53F2[ 40] = { /* code 53F2 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __XX___X,________,
  ____XXX_,________,
  _____XXX,X_______,
  _XXXX___,_XXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_542F[ 40] = { /* code 542F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,________,
  __X_____,________,
  __X_XXXX,XXXXX___,
  __X_X___,____X___,
  _X__X___,____X___,
  _X__XXXX,XXXXX___,
  X___X___,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_5BB9[ 40] = { /* code 5BB9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  _XXXXXXX,XXXXX___,
  _X___X__,XX__X___,
  ___XX_XX,__XX____,
  _XX__XX_,X__XX___,
  ____XX__,_X______,
  __XX____,__XX____,
  XXXXXXXX,XXX_XX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___XXXXX,XXX_____,
  ___X____,__X_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_5F0F[ 40] = { /* code 5F0F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,X_XX____,
  ________,X__X____,
  XXXXXXXX,XXXXXX__,
  ________,X_______,
  ________,X_______,
  _XXXXXX_,X_______,
  ___X____,X_______,
  ___X____,_X______,
  ___X____,_X___X__,
  ___X____,_XX__X__,
  ___XXXXX,__XXXX__,
  XXX_____,___XX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_624B[ 40] = { /* code 624B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,_XXXX___,
  _XXXXXXX,X_______,
  ______X_,________,
  ______X_,________,
  _XXXXXXX,XXXXX___,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXX__,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_635F[ 40] = { /* code 635F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X___XX,XXXX____,
  __X___X_,___X____,
  XXXXX_XX,XXXX____,
  __X___X_,___X____,
  __X_____,________,
  __XXXXXX,XXXXX___,
  XXX__X__,____X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,XX__X___,
  __X____X,X_XXX___,
  XXX_XXX_,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_636E[ 40] = { /* code 636E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X__XXX,XXXXX___,
  __X__X__,____X___,
  XXXXXXXX,XXXXX___,
  __X__X__,____X___,
  __X__X__,_X______,
  __XX_XXX,XXXXXX__,
  XXX__X__,_X______,
  __X__XXX,XXXXX___,
  __X__XX_,____X___,
  __X_X_X_,____X___,
  __X_X_XX,XXXXX___,
  XXXX__X_,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6570[ 40] = { /* code 6570 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X__X__X,_X______,
  __X_XXX_,_X______,
  XXXXXXX_,XXXXXX__,
  ___XX___,X___X___,
  _XXXXX_X,X___X___,
  XX__X_XX,X__XX___,
  ___X____,_X_X____,
  XXXXXXX_,_X_X____,
  _X____X_,__X_____,
  __XXXX__,_XXX____,
  __XX_XXX,X__XX___,
  XX____XX,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6574[ 40] = { /* code 6574 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____X___,_X______,
  XXXXXXX_,XX______,
  _X__X_X_,XXXXXX__,
  _XXXXXXX,X___X___,
  ___XXX__,_X__X___,
  __X_X_X_,__XX____,
  XX__X__X,XX__XX__,
  _XXXXXXX,XXXXX___,
  _______X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_65B9[ 40] = { /* code 65B9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _______X,________,
  XXXXXXXX,XXXXXX__,
  ____X___,________,
  ____X___,________,
  ____XXXX,XXXX____,
  ____X___,___X____,
  ____X___,___X____,
  ___X____,___X____,
  __XX____,___X____,
  _XX_____,__XX____,
  XX____XX,XXX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_65F6[ 40] = { /* code 65F6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,___X____,
  _XXXXX__,___X____,
  _X___X__,___X____,
  _X___XXX,XXXXXX__,
  _X___X__,___X____,
  _XXXXX_X,___X____,
  _X___X__,X__X____,
  _X___X__,X__X____,
  _X___X__,___X____,
  _XXXXX__,___X____,
  _X___X__,___X____,
  ________,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_676F[ 40] = { /* code 676F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X__XXX,XXXXXX__,
  __X_____,_X______,
  XXXXX___,_X______,
  __X_____,X_______,
  _XXX___X,XX______,
  _XX_X__X,_XX_____,
  _XX___X_,_X_X____,
  X_X__X__,_X__X___,
  X_X_X___,_X___X__,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6837[ 40] = { /* code 6837 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X___X_,___X____,
  __X____X,__X_____,
  XXXXXXXX,XXXXX___,
  __X_____,_X______,
  _XX_____,_X______,
  _XXX_XXX,XXXX____,
  _XX_X___,_X______,
  X_X_____,_X______,
  X_X_XXXX,XXXXX___,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6CB9[ 40] = { /* code 6CB9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X______,X_______,
  __X_____,X_______,
  ___X_XXX,XXXXX___,
  _X___X__,X___X___,
  _XX__X__,X___X___,
  __X__X__,X___X___,
  _____XXX,XXXXX___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  _XX__X__,X___X___,
  _X___XXX,XXXXX___,
  _X___X__,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6D41[ 40] = { /* code 6D41 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X______,XX______,
  __X_XXXX,XXXXX___,
  ___X___X,X_______,
  _X____XX,__X_____,
  _XX__X__,___X____,
  __X_XXXX,XXXX____,
  ________,____X___,
  __X__X__,X_X_____,
  __X__X__,X_X_____,
  __X__X__,X_X__X__,
  _X__X___,X_X__X__,
  _X_X____,X_XXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6D4B[ 40] = { /* code 6D4B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X__XXXX,X___X___,
  __X_X___,X_X_X___,
  ___XX_X_,X_X_X___,
  _X__X_X_,X_X_X___,
  _XX_X_X_,X_X_X___,
  __X_X_X_,X_X_X___,
  ____X_X_,X_X_X___,
  __X_X_X_,X_X_X___,
  __X___X_,__X_X___,
  _XX__X_X,____X___,
  _X__XX__,X___X___,
  _X_X____,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_70ED[ 40] = { /* code 70ED */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X____X,________,
  __X____X,________,
  XXXXXXXX,XXXX____,
  __X____X,___X____,
  __XXXXXX,___X____,
  XXX___XX,X__X_X__,
  __X___X_,XX_X_X__,
  XXX_XX__,____XX__,
  ________,________,
  _X__X___,X__X____,
  XX__XX__,XX__X___,
  X____X__,_X___X__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_7387[ 40] = { /* code 7387 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  _XXXXXXX,XXXXXX__,
  ______XX,________,
  _XX__X__,_X__X___,
  ___XXXXX,X_XX____,
  ____X__X,_XX_____,
  __XX_XX_,_X_XX___,
  _X__XXXX,XX___X__,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_7535[ 40] = { /* code 7535 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  ______X_,________,
  _XXXXXXX,XXXX____,
  _X____X_,___X____,
  _X____X_,___X____,
  _XXXXXXX,XXXX____,
  _X____X_,___X____,
  _X____X_,___X____,
  _XXXXXXX,XXXX____,
  _X____X_,_____X__,
  ______X_,_____X__,
  ______XX,XXXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_79EF[ 40] = { /* code 79EF */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XX_XX,XXXXX___,
  XXX___X_,____X___,
  __X___X_,____X___,
  XXXXX_X_,____X___,
  __X___X_,____X___,
  _XX___X_,____X___,
  _XXX__XX,XXXXX___,
  _XX_X_X_,____X___,
  X_X____X,___X____,
  X_X___X_,____X___,
  __X__X__,____X___,
  __X_X___,_____X__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_7A7A[ 40] = { /* code 7A7A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXX___,
  _X______,____X___,
  _X__XX__,XX__X___,
  __XX____,__XX____,
  XX______,____XX__,
  __XXXXXX,XXXX____,
  ______X_,________,
  ______X_,________,
  ______X_,________,
  _XXXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8017[ 40] = { /* code 8017 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X____,__XXX___,
  ___X__XX,XX______,
  XXXXXX__,_X______,
  ___X____,_X______,
  _XXXXXXX,XXXXX___,
  ___X____,_X______,
  XXXXXX__,_X______,
  __XXXXXX,XXXXXX__,
  __XX_X__,_X___X__,
  _X_X____,_X___X__,
  X__X____,_X___X__,
  ___X____,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_81EA[ 40] = { /* code 81EA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8A00[ 40] = { /* code 8A00 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  _XXXXXXX,XXXXX___,
  ________,________,
  __XXXXXX,XXXX____,
  ________,________,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8BD5[ 40] = { /* code 8BD5 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X______,_X_X____,
  __X_____,_X__X___,
  __XX____,_X______,
  __X__XXX,XXXXXX__,
  XXX_____,_X______,
  __X_____,_X______,
  __X_XXXX,XX______,
  __X___X_,_X______,
  __X_X_X_,__X__X__,
  __XXX_X_,__X__X__,
  __X___XX,X_XX_X__,
  _X__XXX_,___XX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8BED[ 40] = { /* code 8BED */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X___XXX,XXXXXX__,
  __X____X,________,
  ___X_XXX,XXXXX___,
  _______X,____X___,
  XXX____X,____X___,
  __X_XXXX,XXXXXX__,
  __X_____,________,
  __X___XX,XXXXX___,
  __X___X_,____X___,
  __X_X_X_,____X___,
  __XX__XX,XXXXX___,
  _X____X_,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8C03[ 40] = { /* code 8C03 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__XXX,XXXXX___,
  __XX_X__,____X___,
  _____X__,X___X___,
  XXX__X_X,XXX_X___,
  __X__X__,X___X___,
  __X__XXX,XXXXX___,
  __X__X__,____X___,
  __X_XX_X,XXX_X___,
  __XX_X_X,__X_X___,
  _X__X__X,XXX_X___,
  ____X__X,____X___,
  ___X____,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8D28[ 40] = { /* code 8D28 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,__XXXX__,
  __XXXXXX,XX______,
  __X_____,X_______,
  __XXXXXX,XXXXX___,
  __X_____,X_______,
  __X_XXXX,XXXX____,
  __X_X___,___X____,
  __X_X___,X__X____,
  __X_X___,X__X____,
  __X_X___,XX_X____,
  _X____XX,_XXX____,
  _X_XXX__,___XX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_949F[ 40] = { /* code 949F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,_X______,
  _X______,_X______,
  _XXXX___,_X______,
  X_____XX,XXXXX___,
  XXXXX_X_,_X__X___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  XXXXX_XX,XXXXX___,
  __X___X_,_X__X___,
  __X_____,_X______,
  __X_X___,_X______,
  __XX____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_963B[ 40] = { /* code 963B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX_XX,XXXX____,
  _X__X_X_,___X____,
  _X_X__X_,___X____,
  _X_X__X_,___X____,
  _X_X__XX,XXXX____,
  _X_X__X_,___X____,
  _X__X_X_,___X____,
  _X__X_XX,XXXX____,
  _X__X_X_,___X____,
  _XXXX_X_,___X____,
  _X____X_,___X____,
  _X__XXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_9891[ 40] = { /* code 9891 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___X__XX,XXXXXX__,
  _X_XXX__,_X______,
  _X_X____,_X______,
  _X_X___X,XXXXX___,
  XXXXXXXX,____X___,
  _______X,_X__X___,
  ___X___X,_X__X___,
  _X_X__XX,_X__X___,
  XX_X_X_X,_X__X___,
  X___X__X,XXX_X___,
  __XX___X,X_XXX___,
  XX___XX_,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontweiruanyahei20_CharInfo[41] = {
   {  14,  14,  2, acGUI_Fontweiruanyahei20_4E00 } /* code 4E00 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_4E0A } /* code 4E0A */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_4E0B } /* code 4E0B */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_4E2A } /* code 4E2A */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_4EA4 } /* code 4EA4 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_4ECB } /* code 4ECB */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_4F53 } /* code 4F53 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_52A0 } /* code 52A0 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_52A8 } /* code 52A8 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_5386 } /* code 5386 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_53F2 } /* code 53F2 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_542F } /* code 542F */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_5BB9 } /* code 5BB9 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_5F0F } /* code 5F0F */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_624B } /* code 624B */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_635F } /* code 635F */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_636E } /* code 636E */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6570 } /* code 6570 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6574 } /* code 6574 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_65B9 } /* code 65B9 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_65F6 } /* code 65F6 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_676F } /* code 676F */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6837 } /* code 6837 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6CB9 } /* code 6CB9 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6D41 } /* code 6D41 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6D4B } /* code 6D4B */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_70ED } /* code 70ED */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_7387 } /* code 7387 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_7535 } /* code 7535 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_79EF } /* code 79EF */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_7A7A } /* code 7A7A */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8017 } /* code 8017 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_81EA } /* code 81EA */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8A00 } /* code 8A00 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8BD5 } /* code 8BD5 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8BED } /* code 8BED */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8C03 } /* code 8C03 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8D28 } /* code 8D28 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_949F } /* code 949F */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_963B } /* code 963B */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_9891 } /* code 9891 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop40 = {
   0x9891 /* first character */
  ,0x9891 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 40] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop39 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 39] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop38 = {
   0x949F /* first character */
  ,0x949F /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 38] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop37 = {
   0x8D28 /* first character */
  ,0x8D28 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 37] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop36 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 36] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop35 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 35] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop34 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop33 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop32 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop31 = {
   0x8017 /* first character */
  ,0x8017 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop30 = {
   0x7A7A /* first character */
  ,0x7A7A /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop29 = {
   0x79EF /* first character */
  ,0x79EF /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop28 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop27 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop26 = {
   0x70ED /* first character */
  ,0x70ED /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop25 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop24 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop23 = {
   0x6CB9 /* first character */
  ,0x6CB9 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop22 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop21 = {
   0x676F /* first character */
  ,0x676F /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop20 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop19 = {
   0x65B9 /* first character */
  ,0x65B9 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop18 = {
   0x6574 /* first character */
  ,0x6574 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop17 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop16 = {
   0x636E /* first character */
  ,0x636E /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop15 = {
   0x635F /* first character */
  ,0x635F /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop14 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop13 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop12 = {
   0x5BB9 /* first character */
  ,0x5BB9 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop11 = {
   0x542F /* first character */
  ,0x542F /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop10 = {
   0x53F2 /* first character */
  ,0x53F2 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop9 = {
   0x5386 /* first character */
  ,0x5386 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  9] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop8 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  8] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop7 = {
   0x52A0 /* first character */
  ,0x52A0 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  7] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop6 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  6] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop5 = {
   0x4ECB /* first character */
  ,0x4ECB /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  5] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop4 = {
   0x4EA4 /* first character */
  ,0x4EA4 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  4] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop3 = {
   0x4E2A /* first character */
  ,0x4E2A /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  3] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop2 = {
   0x4E0A /* first character */
  ,0x4E0B /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  1] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop1 = {
   0x4E00 /* first character */
  ,0x4E00 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  0] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontweiruanyahei20 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontweiruanyahei20_Prop1}
  ,16 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

