/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: weiruanyahei20.c                                      *
* Font:        微软雅黑                                              *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x6CB9 (27833)                                *
* Character enabled:   0x6CB9 (27833)                                *
* Character enabled:   0x6837 (26679)                                *
* Character enabled:   0x6D4B (27979)                                *
* Character enabled:   0x5386 (21382)                                *
* Character enabled:   0x53F2 (21490)                                *
* Character enabled:   0x6570 (25968)                                *
* Character enabled:   0x636E (25454)                                *
* Character enabled:   0x8C03 (35843)                                *
* Character enabled:   0x6574 (25972)                                *
* Character enabled:   0x65F6 (26102)                                *
* Character enabled:   0x949F (38047)                                *
* Character enabled:   0x8BED (35821)                                *
* Character enabled:   0x8AFD (35581)                                *
* Character enabled:   0x8A00 (35328)                                *
* Character disabled:  0x8AFD (35581)                                *
* Character enabled:   0x8BD5 (35797)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontweiruanyahei20;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_5386[ 40] = { /* code 5386 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,________,
  __X____X,________,
  __X____X,________,
  __X_XXXX,XXXX____,
  __X____X,___X____,
  __X____X,___X____,
  __X____X,___X____,
  __X___X_,___X____,
  _X___XX_,___X____,
  _X__XX__,___X____,
  X__XX___,XXX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_53F2[ 40] = { /* code 53F2 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __XX___X,________,
  ____XXX_,________,
  _____XXX,X_______,
  _XXXX___,_XXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_636E[ 40] = { /* code 636E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X__XXX,XXXXX___,
  __X__X__,____X___,
  XXXXXXXX,XXXXX___,
  __X__X__,____X___,
  __X__X__,_X______,
  __XX_XXX,XXXXXX__,
  XXX__X__,_X______,
  __X__XXX,XXXXX___,
  __X__XX_,____X___,
  __X_X_X_,____X___,
  __X_X_XX,XXXXX___,
  XXXX__X_,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6570[ 40] = { /* code 6570 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X__X__X,_X______,
  __X_XXX_,_X______,
  XXXXXXX_,XXXXXX__,
  ___XX___,X___X___,
  _XXXXX_X,X___X___,
  XX__X_XX,X__XX___,
  ___X____,_X_X____,
  XXXXXXX_,_X_X____,
  _X____X_,__X_____,
  __XXXX__,_XXX____,
  __XX_XXX,X__XX___,
  XX____XX,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6574[ 40] = { /* code 6574 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____X___,_X______,
  XXXXXXX_,XX______,
  _X__X_X_,XXXXXX__,
  _XXXXXXX,X___X___,
  ___XXX__,_X__X___,
  __X_X_X_,__XX____,
  XX__X__X,XX__XX__,
  _XXXXXXX,XXXXX___,
  _______X,________,
  ___X___X,XXXXX___,
  ___X___X,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_65F6[ 40] = { /* code 65F6 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,___X____,
  _XXXXX__,___X____,
  _X___X__,___X____,
  _X___XXX,XXXXXX__,
  _X___X__,___X____,
  _XXXXX_X,___X____,
  _X___X__,X__X____,
  _X___X__,X__X____,
  _X___X__,___X____,
  _XXXXX__,___X____,
  _X___X__,___X____,
  ________,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6837[ 40] = { /* code 6837 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X___X_,___X____,
  __X____X,__X_____,
  XXXXXXXX,XXXXX___,
  __X_____,_X______,
  _XX_____,_X______,
  _XXX_XXX,XXXX____,
  _XX_X___,_X______,
  X_X_____,_X______,
  X_X_XXXX,XXXXX___,
  __X_____,_X______,
  __X_____,_X______,
  __X_____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6CB9[ 40] = { /* code 6CB9 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X______,X_______,
  __X_____,X_______,
  ___X_XXX,XXXXX___,
  _X___X__,X___X___,
  _XX__X__,X___X___,
  __X__X__,X___X___,
  _____XXX,XXXXX___,
  __X__X__,X___X___,
  __X__X__,X___X___,
  _XX__X__,X___X___,
  _X___XXX,XXXXX___,
  _X___X__,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_6D4B[ 40] = { /* code 6D4B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X__XXXX,X___X___,
  __X_X___,X_X_X___,
  ___XX_X_,X_X_X___,
  _X__X_X_,X_X_X___,
  _XX_X_X_,X_X_X___,
  __X_X_X_,X_X_X___,
  ____X_X_,X_X_X___,
  __X_X_X_,X_X_X___,
  __X___X_,__X_X___,
  _XX__X_X,____X___,
  _X__XX__,X___X___,
  _X_X____,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8A00[ 40] = { /* code 8A00 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,________,
  XXXXXXXX,XXXXXX__,
  ________,________,
  _XXXXXXX,XXXXX___,
  ________,________,
  __XXXXXX,XXXX____,
  ________,________,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8BD5[ 40] = { /* code 8BD5 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X______,_X_X____,
  __X_____,_X__X___,
  __XX____,_X______,
  __X__XXX,XXXXXX__,
  XXX_____,_X______,
  __X_____,_X______,
  __X_XXXX,XX______,
  __X___X_,_X______,
  __X_X_X_,__X__X__,
  __XXX_X_,__X__X__,
  __X___XX,X_XX_X__,
  _X__XXX_,___XX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8BED[ 40] = { /* code 8BED */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X___XXX,XXXXXX__,
  __X____X,________,
  ___X_XXX,XXXXX___,
  _______X,____X___,
  XXX____X,____X___,
  __X_XXXX,XXXXXX__,
  __X_____,________,
  __X___XX,XXXXX___,
  __X___X_,____X___,
  __X_X_X_,____X___,
  __XX__XX,XXXXX___,
  _X____X_,____X___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_8C03[ 40] = { /* code 8C03 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__XXX,XXXXX___,
  __XX_X__,____X___,
  _____X__,X___X___,
  XXX__X_X,XXX_X___,
  __X__X__,X___X___,
  __X__XXX,XXXXX___,
  __X__X__,____X___,
  __X_XX_X,XXX_X___,
  __XX_X_X,__X_X___,
  _X__X__X,XXX_X___,
  ____X__X,____X___,
  ___X____,_XXXX___,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontweiruanyahei20_949F[ 40] = { /* code 949F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X_____,_X______,
  _X______,_X______,
  _XXXX___,_X______,
  X_____XX,XXXXX___,
  XXXXX_X_,_X__X___,
  __X___X_,_X__X___,
  __X___X_,_X__X___,
  XXXXX_XX,XXXXX___,
  __X___X_,_X__X___,
  __X_____,_X______,
  __X_X___,_X______,
  __XX____,_X______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontweiruanyahei20_CharInfo[14] = {
   {  14,  14,  2, acGUI_Fontweiruanyahei20_5386 } /* code 5386 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_53F2 } /* code 53F2 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_636E } /* code 636E */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6570 } /* code 6570 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6574 } /* code 6574 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_65F6 } /* code 65F6 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6837 } /* code 6837 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6CB9 } /* code 6CB9 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_6D4B } /* code 6D4B */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8A00 } /* code 8A00 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8BD5 } /* code 8BD5 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8BED } /* code 8BED */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_8C03 } /* code 8C03 */
  ,{  14,  14,  2, acGUI_Fontweiruanyahei20_949F } /* code 949F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop14 = {
   0x949F /* first character */
  ,0x949F /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 13] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop13 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop12 = {
   0x8BED /* first character */
  ,0x8BED /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop11 = {
   0x8BD5 /* first character */
  ,0x8BD5 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop10 = {
   0x8A00 /* first character */
  ,0x8A00 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  9] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop9 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  8] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop8 = {
   0x6CB9 /* first character */
  ,0x6CB9 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  7] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop7 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  6] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop6 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  5] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop5 = {
   0x6574 /* first character */
  ,0x6574 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  4] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop4 = {
   0x6570 /* first character */
  ,0x6570 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  3] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop3 = {
   0x636E /* first character */
  ,0x636E /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  2] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop2 = {
   0x53F2 /* first character */
  ,0x53F2 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  1] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontweiruanyahei20_Prop1 = {
   0x5386 /* first character */
  ,0x5386 /* last character  */
  ,&GUI_Fontweiruanyahei20_CharInfo[  0] /* address of first character */
  ,&GUI_Fontweiruanyahei20_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontweiruanyahei20 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontweiruanyahei20_Prop1}
  ,16 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

