/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.20                          *
*        Compiled Mar 19 2013, 15:01:00                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include <stdint.h>
#include "..\drv\fm31256\fm31256.h"
#include "..\drv\t6963\t6963.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_BUTTON_0    (GUI_ID_USER + 0x02)
#define ID_BUTTON_1    (GUI_ID_USER + 0x03)
#define ID_BUTTON_2    (GUI_ID_USER + 0x04)
#define ID_BUTTON_3    (GUI_ID_USER + 0x05)
#define ID_TEXT_0    (GUI_ID_USER + 0x06)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontweiruanyahei20;
WM_HWIN hItem_Text_Time = NULL;
static WM_HWIN        _mainWin;
static WM_HWIN        _testFrame;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "MainWindow", ID_WINDOW_0, 0, 0, 240, 128, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "油样测试", ID_BUTTON_0, 60, 5, 100, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "历史数据", ID_BUTTON_1, 60, 30, 100, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "调整时钟", ID_BUTTON_2, 60, 55, 100, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "语    言", ID_BUTTON_3, 60, 80, 100, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "2014-05-08 12:00", ID_TEXT_0, 140, 113, 100, 15, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void _cb_DialogInit (WM_MESSAGE * pMsg)
{
	WM_HWIN hWin = pMsg->hWin;
	GUI_UC_SetEncodeUTF8();
    BUTTON_SetFont(WM_GetDialogItem(hWin,GUI_ID_BUTTON0),&GUI_Fontweiruanyahei20);
	BUTTON_SetFont(WM_GetDialogItem(hWin,GUI_ID_BUTTON1),&GUI_Fontweiruanyahei20);
	BUTTON_SetFont(WM_GetDialogItem(hWin,GUI_ID_BUTTON2),&GUI_Fontweiruanyahei20);
	BUTTON_SetFont(WM_GetDialogItem(hWin,GUI_ID_BUTTON3),&GUI_Fontweiruanyahei20);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END
  switch (pMsg->MsgId) {
	  
  case WM_INIT_DIALOG:
    //
    // Initialization of '2014-05-08 12:00'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
	hItem_Text_Time = hItem;//保存hitem 用于更新时间
	//TEXT_SetText (hItem, "123456789");
    // USER START (Optionally insert additional code for further widget initialization)
	//_cb_DialogInit(pMsg);
	GUI_UC_SetEncodeUTF8();
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem,&GUI_Fontweiruanyahei20);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
	BUTTON_SetFont(hItem,&GUI_Fontweiruanyahei20);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
	BUTTON_SetFont(hItem,&GUI_Fontweiruanyahei20);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
	BUTTON_SetFont(hItem,&GUI_Fontweiruanyahei20);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'bb'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
		//_mainWin = WM_GetFocussedWindow();
		//WM_DeleteWindow(pMsg->hWin);
		//WM_DeleteWindow(pMsg->hWin);
		//GUI_Init();
		//CreateTestFrame ();
		WM_ShowWindow(_testFrame);
		WM_HideWindow(_mainWin);
		WM_SetFocus (_testFrame);	  	
		//GUI_Init();
		//CreateTestFrame();
        //USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'bbb'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'bbbb'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'bbbbb'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMainWindow
*/
WM_HWIN CreateMainWindow(void);
WM_HWIN CreateMainWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void TimeUpdata (void)
{
	uint8_t data[7],i=0;
	int8_t datastr[20];
	if(hItem_Text_Time == NULL){
		
	}else{
		FM31256_GetTime (data);
		datastr[i++] = '2';
		datastr[i++] = '0';
		datastr[i++] = (data[6]>>4)+'0';
		datastr[i++] = (data[6]&0xf)+'0';
		datastr[i++] = '-';
		datastr[i++] = (data[5]>>4)+'0';
		datastr[i++] = (data[5]&0xf)+'0';
		datastr[i++] = '-';
		datastr[i++] = (data[4]>>4)+'0';
		datastr[i++] = (data[4]&0xf)+'0';
		datastr[i++] = ' ';
		datastr[i++] = (data[2]>>4)+'0';
		datastr[i++] = (data[2]&0xf)+'0';
		datastr[i++] = ':';
		datastr[i++] = (data[1]>>4)+'0';
		datastr[i++] = (data[1]&0xf)+'0';
		datastr[i++] = 0;
		TEXT_SetText (hItem_Text_Time, datastr);
	}
	
}
//指向主窗体
void Mainwin_SetFocus (void)
{	
	WM_ShowWindow(_mainWin);
	WM_HideWindow(_testFrame);
	WM_SetFocus (_mainWin);	
}
void MainTask (void)
{
	GUI_Init();
	//WM_SetCreateFlags(WM_CF_MEMDEV);
	//WM_SelectWindow(WM_HBKWIN);
	//GUI_UC_SetEncodeUTF8();
	//GUI_SetFont (&GUI_Fontweiruanyahei20);
	//GUI_DispStringAt("油样", 20, 30);
	//while(1);	
	_testFrame = CreateTestFrame();	
 	_mainWin = CreateMainWindow();
 	WM_HideWindow(_testFrame);
	//GUI_Exec ();
//	while(1);
// 	//WM_InvalidateWindow (_mainWin);
//  	while(1)
//  	{
// // 		WM_ShowWindow(_mainWin);
// // 		WM_HideWindow(_testFrame);
// //  	GUI_Delay (100);
// // 		WM_HideWindow(_mainWin);
// // 		WM_ShowWindow(_testFrame);
// 		GUI_Delay (10);
//  	}
// 	GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), &_cbDialog, 0, 0, 0);
// 	while(1){
// 		printf("\r\ndelay");
// 		GUI_Delay (10);
// 	}	
}
// USER END

/*************************** End of file ****************************/
