/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.20                          *
*        Compiled Mar 19 2013, 15:01:00                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0     (GUI_ID_USER + 0x03)
#define ID_TEXT_0     (GUI_ID_USER + 0x07)
#define ID_BUTTON_1     (GUI_ID_USER + 0x08)
#define ID_BUTTON_2     (GUI_ID_USER + 0x09)
#define ID_BUTTON_3     (GUI_ID_USER + 0x0A)
#define ID_TEXT_1     (GUI_ID_USER + 0x10)
#define ID_TEXT_2     (GUI_ID_USER + 0x11)
#define ID_TEXT_3     (GUI_ID_USER + 0x12)
#define ID_TEXT_4     (GUI_ID_USER + 0x13)
#define ID_TEXT_5     (GUI_ID_USER + 0x14)


// USER START (Optionally insert additional defines)
extern WM_HWIN CreateTest(void);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontweiruanyahei20;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 128, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "油样", ID_BUTTON_0, 80, 5, 96, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "2014-03-19 12:00", ID_TEXT_0, 148, 113, 92, 14, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Data", ID_BUTTON_1, 80, 34, 96, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Settime", ID_BUTTON_2, 80, 63, 96, 24, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Language", ID_BUTTON_3, 80, 91, 96, 24, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "English", ID_TEXT_1, 185, 97, 39, 15, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "F", ID_TEXT_2, 20, 0, 32, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "J", ID_TEXT_3, 20, 32, 32, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "P", ID_TEXT_4, 20, 64, 32, 32, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "H", ID_TEXT_5, 20, 96, 32, 32, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
	WM_HWIN hWin = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
    //
    // Initialization of '2014-05-08 12:00'
    //
    // USER START (Optionally insert additional code for further widget initialization)
	//_cb_DialogInit(pMsg);
	GUI_UC_SetEncodeUTF8();
    BUTTON_SetFont(WM_GetDialogItem(pMsg->hWin,GUI_ID_BUTTON0),&GUI_Fontweiruanyahei20);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Test'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)

        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Data'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Settime'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Language'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void MainTask (void)
{
	GUI_ExecDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	CreateWindow ();
	while(1){
		GUI_Delay (10);
	}
}
// USER END

/*************************** End of file ****************************/
